name: ludo
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ludoboard.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
